CREATE TABLE IF NOT EXISTS 'wifi' ( 
	timestamp TIMESTAMP,
	ap_id SYMBOL CAPACITY 33554432 CACHE,
	avg_rssi DOUBLE,
	unique_sessions INT,
	max_noise_floor DOUBLE,
	avg_noise_floor DOUBLE,
	avg_snr DOUBLE,
	total_bytes_in LONG,
	total_bytes_out LONG,
	total_packets_in LONG,
	total_packets_out LONG,
	avg_throughput_mbps DOUBLE,
	total_retries LONG,
	total_errors LONG,
	avg_tx_power DOUBLE,
	avg_rx_power DOUBLE,
	avg_tx_rate DOUBLE,
	avg_rx_rate DOUBLE,
	avg_mcs_tx DOUBLE,
	avg_mcs_rx DOUBLE,
	max_assoc_clients INT,
	total_roam_events INT,
	avg_ap_temperature DOUBLE,
	max_uptime_sec LONG,
	fw_version SYMBOL CAPACITY 256 CACHE,
	channel SYMBOL CAPACITY 256 CACHE,
	channel_width SYMBOL CAPACITY 256 CACHE,
	longitude DOUBLE,
	latitude DOUBLE,
	state SYMBOL CAPACITY 256 CACHE,
	region SYMBOL CAPACITY 256 CACHE,
	band SYMBOL CAPACITY 256 CACHE,
	vendor_source SYMBOL CAPACITY 256 CACHE,
	vendor_name SYMBOL CAPACITY 256 CACHE,
	model SYMBOL CAPACITY 256 CACHE,
	ssid SYMBOL CAPACITY 256 CACHE
) timestamp(timestamp) PARTITION BY HOUR TTL 2 WEEKS WAL
WITH maxUncommittedRows=500000, o3MaxLag=600000000us
DEDUP UPSERT KEYS(timestamp,ap_id);
