from sqlalchemy import Column, Integer, BigInteger, Float, String, DateTime
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class WiFi(Base):
    __tablename__ = 'wifi'

    timestamp = Column(DateTime, primary_key=True)
    ap_id = Column(String, primary_key=True, index=True)
    avg_rssi = Column(Float)
    unique_sessions = Column(Integer)
    max_noise_floor = Column(Float)
    avg_noise_floor = Column(Float)
    avg_snr = Column(Float)
    total_bytes_in = Column(BigInteger)
    total_bytes_out = Column(BigInteger)
    total_packets_in = Column(BigInteger)
    total_packets_out = Column(BigInteger)
    avg_throughput_mbps = Column(Float)
    total_retries = Column(BigInteger)
    total_errors = Column(BigInteger)
    avg_tx_power = Column(Float)
    avg_rx_power = Column(Float)
    avg_tx_rate = Column(Float)
    avg_rx_rate = Column(Float)
    avg_mcs_tx = Column(Float)
    avg_mcs_rx = Column(Float)
    max_assoc_clients = Column(Integer)
    total_roam_events = Column(Integer)
    avg_ap_temperature = Column(Float)
    max_uptime_sec = Column(BigInteger)
    fw_version = Column(String)
    channel = Column(String, index=True)
    channel_width = Column(String)
    longitude = Column(Float)
    latitude = Column(Float)
    state = Column(String, index=True)
    region = Column(String, index=True)
    band = Column(String, index=True)
    vendor_source = Column(String)
    vendor_name = Column(String)
    model = Column(String)
    ssid = Column(String)
